FROM node:10-alpine

COPY ./fetch ./fetch
COPY ./guanyu-core ./guanyu-core

RUN cd /fetch && npm install && npm dedupe
RUN cd /guanyu-core && npm install && npm dedupe

WORKDIR /fetch

CMD ["npm", "run", "dev"]
