FROM clifflu/sophos-av-npm

COPY ./sophosav ./sophosav
COPY ./guanyu-core ./guanyu-core

RUN cd /sophosav && npm install && npm dedupe
RUN cd /guanyu-core && npm install && npm dedupe
RUN sed -i "s/<Email><Status>enabled/<Email><Status>disabled/" /opt/sophos-av/etc/savd.cfg

WORKDIR /sophosav

CMD ["npm", "run", "dev"]